#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>

#define MSG_WELCOME "WELCOME TO SORTIFY!"
#define MSG_SORT "Sort the following numbers:"
#define MSG_SORT2 "Please sort the numbers"
#define MSG_WELL "Well done!"
#define MSG_WIN "Congratulations, you win!"
#define MSG_OVER "Game Over."
#define MSG_WRONG "Wrong answer."
#define MSG_MAX "You have reached the maximum number of moves."
#define MSG_BYE "Bye."
#define MSG_UNKNOWN "Unknown option."
/* Use puts() to print constant strings */

int rand_number(const int, const int);
void print_status( int, int, int);
void print_menu(void);
void player_options(char);
int rand_number(const int min, const int max);




int main(int argc, char **argv)
{

	puts(MSG_WELCOME);
    print_menu();
	int seed;
	int level = 1, score = 0, plays = 0;
	char player_command;
	if (argc > 1)
	{
		seed = atoi(argv[1]);
	}
	else
	{
		seed = time(NULL);
	}
}

/*Function to print Menu*/

void print_menu(void)
{
	puts("+-----------------------------+");
	puts("| SORTIFY                     |");
	puts("| p - next chalenge           |");
	puts("| q - quit                    |");
	puts("| m - print this information  |");
	puts("| s - show your status        |");
	puts("+-----------------------------+");
}

/*Fucntion for Player Commands*/
void player_options(char player_command)
{
    do
    {
        scanf(" %c", &player_command);
		switch (player_command)
        {
            case 'p':
                
                break;

            case 'q':
                puts(MSG_BYE);
                break;
            
            case 'm':
                print_menu();
                break;

            case 's':
                print_status(const int level, const int score, const int plays);
                break;

            default:
                printf("Unknown option\n");
                break;
        }

    }
    while (player_command != 'q');
    
    
}

/* Function to print game status*/
void print_status( int level,  int score,  int plays)
{ 
	puts("+-----------------------------+");
	printf("| level:  %02d                  |\n", level);
	printf("| points: %02d                  |\n", score);
	printf("| plays:  %02d                  |\n", plays);
	puts("+-----------------------------+");
}



/* generate a random integer between min and max and saves it in an array */
int rand_number(const int min, const int max)
{
	int i,j,k,num1,num2,num3,num4;
	if (max < min)
	{
		puts("Max must be larger than Min");
		exit(0);
	}
	
	int number,sorted,maior;
	int n = abs(max - min) + 1;
    int numberlist[4]={0},numberinput[4]={0},numberlistaux[4]={0}; /*new*/
	for ( i = 0 ; i < 3; i++)
	{
		number = ((rand() % n) + min);
        numberlist[i]=number; /*new*/
		printf("%d, " , number);
    
	}    

    scanf("%d %d %d %d",&num1,&num2,&num3,&num4);

    numberinput[4]={num1,num2,num3,num4};

/*Orders the list generated by ascending order */
    while (sorted!=1)
    {
        sorted=1;
        for(i=0;i<=2;i++)
        {
            if (numberlist[i]>numberlist[i+1])
            {
                maior = numberlist[i];
                numberlist[i]=numberlist[i+1];
                numberlist[i+1]=maior;
                sorted = 0;
            }
        }
    }





	return 0;

}

int 